wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 5
image_size:
  desc: null
  value: 576
batch_size:
  desc: null
  value: 2
gpu:
  desc: null
  value: true
betas:
  desc: null
  value:
  - 0.9
  - 0.999
weight_decay:
  desc: null
  value: 1.0e-08
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699131290.261371
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
