wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 5
image_size:
  desc: null
  value: 572
batch_size:
  desc: null
  value: 4
gpu:
  desc: null
  value: true
momentum:
  desc: null
  value: 0.99
weight_decay:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698211061.413987
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 3
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
